### ISSUE TITLE
ENV["JULIA_STACKTRACE_MINIMAL"] = true doesn't apply for non-interactive errors

### ISSUE THREAD

**Issue by jarbus** [BioTurboNick/AbbreviatedStackTraces.jl#53]
Love this project, it'll save me a lot of scrolling. I'm noticing that the minimal display doesn't work on non-interactive cases:
```julia
File: a.jl
ENV["JULIA_STACKTRACE_MINIMAL"] = true
using AbbreviatedStackTraces
sum([])
```

```
$ julia a.jl
ERROR: LoadError: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T at missing.jl:105
  zero(::Union{Type{P}, P}) where P<:Dates.Period at /usr/share/julia/stdlib/v1.8/Dates/src/periods.jl:53
  zero(::LinearAlgebra.Diagonal) at /usr/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:381
  ...
Stacktrace:
  [1-16] ⋮ internal @ Base, Unknown
    [17] sum(a::Vector{Any})
       @ Base ./reducedim.jl:994
    [18] top-level scope
       @ ~/a.jl:5
Use `err` to retrieve the full stack trace.
```

**Comment by BioTurboNick** [comment]
Glad you like it! 

The default intention is that non-interactive cases shouldn't abbreviate, because the Julia maintainers were concerned about losing debug info from, e.g., cluster runs. So, I suspect there's some conflict there that I should fix.

But, you may be able to make it work as you intend it by setting `ENV["JULIA_STACKTRACE_ABBREVIATED"] = true`, which is what is meant to allow abbreviation during non-interactive use.

**Comment by BioTurboNick** [comment]
I haven't been able to reproduce what you specifically see on Julia 1.8.5, but I have found that with `ENV["JULIA_STACKTRACE_ABBREVIATED"] = true`, no stack trace is output at all.

Can you tell me any more? Like Julia version, OS?

**Comment by BioTurboNick** [comment]
Ah, got it. You must already be setting that, it just isn't applying the minimal style to the visible frames. And figured out the issue, fix is coming.

**Comment by jarbus** [comment]
Thank you!!! And yes, I forgot I threw the abbreviated stack frames in my startup.jl
