### ISSUE TITLE
Collapse internal stacktraces between start and end

### ISSUE THREAD

**Issue by ParadaCarleton** [BioTurboNick/AbbreviatedStackTraces.jl#69]
For example, when broadcasting I get these kinds of messages clogging the stacktrace:
```julia-repl
     [7] _broadcast_getindex_evalf
       @ Main.Wrangling ./broadcast.jl:709 [inlined]
     [8] _broadcast_getindex
       @ Main.Wrangling ./broadcast.jl:682 [inlined]
     [9] getindex
       @ Main.Wrangling ./broadcast.jl:636 [inlined]
    [10] copy
       @ Main.Wrangling ./broadcast.jl:918 [inlined]
    [11] materialize
       @ Main.Wrangling ./broadcast.jl:903 [inlined]
```

**Comment by BioTurboNick** [comment]
I believe the issue is that these functions are being listed as `Main.Wrangling` (because it was pulling from the last non-inlined frame's Module) rather than in `Base` in Julia 1.10, a bug. It was fixed and has been backported to the 1.10 branch, but just missed the beta3 release window. I assumed it made it in, but I guess not. In the meantime I'll add the patch back to this package.

**Comment by BioTurboNick** [comment]
Wait, it's supposed to be there already... can you please tell me what `methods(Base.StackTraces.lookup)` shows? And does this evaluate to true? `v"1.10-DEV.0" < VERSION < v"1.10" || v"1.11-DEV.0" < VERSION < v"1.11-alpha"`

Seems to be working on my system...
```
julia> versioninfo()
Julia Version 1.10.0-beta3
Commit 404750f858 (2023-10-03 12:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_USE_CLI_GIT = true
```

**Comment by BioTurboNick** [comment]
Make sure you have the most recent version, too. v0.2.3
